services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    env_file:
      - .env/.env.dev
    environment:
      SURREAL_USER: ${SURREAL_USER}
      SURREAL_PASS: ${SURREAL_PASS}
    command: start --log debug --user ${SURREAL_USER} --pass ${SURREAL_PASS} --bind 0.0.0.0:8080
    volumes:
      - app:/data
    ports:
      - "8080:8080"
    networks:
      - backend_network


  backend:
    build:
      context: .                  
      dockerfile: ./backend/Dockerfile
    depends_on:
      - surrealdb
    environment:
      DATABASE_URL: "surrealdb:8080"
      DATABASE_NAME: "TEST"
    env_file:
      - .env/.env.${ENV}
    ports:
      - "8000:8000"
      - "80:80"
    networks:
      - backend_network

volumes:
  app:

networks:
  backend_network:
    driver: bridge

